const codes = {
  '1':'Glenfarclas',
'2':'Glenlivet',
'3':'Bowmore',
'4':'Highland Park',
'5':'Auchentoshan',
'6':'Glen Deveron (Macduff Distillery)',
'7':'Longmorn',
'8':'Tamdhu',
'9':'Glen Grant',
'10':'Bunnahabhain',
'11':'Tomatin',
'12':'Benriach',
'13':'Dalmore',
'14':'Talisker',
'15':'Glenfiddich',
'16':'Glenturret',
'17':'Scapa',
'18':'Inchgower',
'19':'Glen Garioch',
'20':'Inverleven',
'21':'Glenglassaugh',
'22':'Glenkinchie',
'23':'Bruichladdich',
'24':'Macallan',
'25':'Rosebank',
'26':'Clynelish',
'27':'Springbank',
'28':'Tullibardine',
'29':'Laphroaig',
'30':'Glenrothes',
'31':'Isle of Jura',
'32':'Edradour',
'33':'Ardbeg',
'34':'Tamnavulin',
'35':'Glen Moray',
'36':'Benrinnes',
'37':'Cragganmore',
'38':'Caperdonich',
'39':'Linkwood',
'40':'Balvenie',
'41':'Dailuaine',
'42':'Tobermory / Ledaig',
'43':'Port Ellen',
'44':'Craigellachie',
'45':'Dallas Dhu',
'46':'Glenlossie',
'47':'Benromach',
'48':'Balmenach',
'49':'Linlithgow / St. Magdalene',
'50':'Bladnoch',
'51':'Bushmills',
'52':'Old Pulteney',
'53':'Caol Ila',
'54':'Aberlour',
'55':'Royal Brackla',
'56':'Coleburn',
'57':'Glen Mhor',
'58':'Strathisla',
'59':'Teaninich',
'60':'Aberfeldy',
'61':'Brora',
'62':'Glenlochy',
'63':'Glentauchers',
'64':'Mannochmore',
'65':'Imperial',
'66':'Ardmore',
'67':'Banff',
'68':'Blair Athol',
'69':'Glen Albyn',
'70':'Balblair',
'71':'Glenburgie',
'72':'Miltonduff',
'73':'Aultmore',
'74':'North Port',
'75':'Glenury / Glenury Royal',
'76':'Mortlach',
'77':'Glen Ord / Glenordie',
'78':'Ben Nevis',
'79':'Deanston',
'80':'Glen Spey',
'81':'Glen Keith',
'82':'Glencadam',
'83':'Convalmore',
'84':'Glendullan',
'85':'Glen Elgin',
'86':'Glenesk',
'87':'Millburn',
'88':'Speyburn',
'89':'Tomintoul',
'90':'Pittyvaich',
'91':'Dufftown',
'92':'Lochside',
'93':'Glen Scotia',
'94':'Fettercairn',
'95':'Auchroisk / Singleton',
'96':'Glendronach',
'97':'Littlemill',
'98':'Lomond (Inverleven Distillery)',
'99':'Glenugie',
'100':'Strathmill',
'101':'Knockando',
'102':'Dalwhinnie',
'103':'Royal Lochnagar',
'104':'Glencraig (Glenburgie Distillery)',
'105':'Tormore',
'106':'Cardhu',
'107':'Glenallachie',
'108':'Allt-a-Bhainne',
'109':'Mosstowie (Miltonduff Distillery)',
'110':'Oban',
'111':'Lagavulin',
'112':'Inchmurrin (Loch Lomond Distillery)',
'113':'Braes of Glenlivet (Braeval Distillery)',
'114':'Longrow (Springbank Distillery)',
'115':'AnCnoc (Knockdhu Distillery)',
'116':'Yoichi',
'117':'Cooley (Unpeated)',
'118':'Cooley / Connemara (Peated)',
'119':'Yamazaki',
'120':'Hakushu',
'121':'Isle of Arran',
'122':'Croftengea (Loch Lomond Distillery)',
'123':'Glengoyne',
'124':'Miyagikyo',
'125':'Glenmorangie',
'126':'Hazelburn (Springbank Distillery)',
'127':'Port Charlotte (Bruichladdich Distillery)',
'128':'Penderyn',
'129':'Kilchoman',
'130':'Chichibu',
'131':'Hanyu',
'132':'Karuizawa',
'133':'Westland',
'134':'Paul John',
'135':'Inchmoan (Loch Lomond Distillery)',
'136':'Eden Mill',
'137':'English Whisky Company (St. George’s Distillery)',
'138':'Omar (Nantou Distillery)',
'139':'Kavalan',
'140':'Balcones',
'141':'Fary Lochan',
'142':'Breuckelen Distilling',
'143':'Copperworks Distilling Company',
'144':'High Coast Distillery',
'145':'Smögen Whisky',
'146':'Cotswolds Distillery',
'147':'Archie Rose Distilling',
'148':'Starward (New World Whisky Distillery)',
'149':'Ardnamurchan',
'G1':'North British',
'G2':'Carsebridge',
'G3':'Caledonian',
'G4':'Cameronbridge',
'G5':'Invergordon',
'G6':'Port Dundas',
'G7':'Girvan',
'G8':'Cambus',
'G9':'Loch Lomond',
'G10':'Strathclyde',
'G11':'Nikka Coffey Grain',
'G12':'Nikka Coffey Malt',
'G13':'Chita',
'G14':'Dumbarton',
'G15':'Rhosdhu (Loch Lomond Distillery)',
'B1':'Heaven Hill',
'B2':'Bernheim',
'B3':'Rock Town',
'B4':'F.E.W',
'B5':'George Dickel (Cascade Hollow)',
'B6':'Finger Lakes Distilling',
'RW1':'F.E.W',
'RW2':'Finger Lakes Distilling',
'RW3':'New York Distilling Company',
'A1':'Chateau de Lacaze',
'A2':'Domaine Laguille',
'A3':'J. Goudoulin',
'A4':'Domaine d’Espérance',
'A5':'Chateau de Laubade',
'A6':'Domaine Lasalle',
'C1':'Camus',
'C2':'Domaine de Chez Guérive',
'C3':'Louis Royer',
'C4':'Distillery D’Aumagne',
'C5':'Tiffon Cognac',
'C6':'M & H Bonneau',
'C7':'Guy Rateau PC',
'C8':'Marie C Bodit GC',
'C9':'Robert Audebeau PC',
'GN1':'Makar (The Glasgow Distillery Company)',
'GN2':'Strathearn Distillery',
'GN3':'Borders Distillery',
'GN4':'Boatyard Distillery',
'GN5':'Glenrinnes Distillery',
'R1':'Monymusk',
'R2':'El Dorado (Demerara Distillers)',
'R3':'West Indies Rum Distillery',
'R4':'Angostura (Trinidad Distillers)',
'R5':'Long Pond Distillery',
'R6':'Foursquare',
'R7':'Hampden Distillery',
'R8':'Compañía Licorera de Nicaragua (Flor de Caña)',
'R9':'Varela Hermanos (Ron Abuelo)',
'R10':'Trinidad Distiller’s',
'R11':'Worthy Park',
'R12':'Travellers',
'R13':'Caroni',
'R14':'Uitvlugt'
};


function replaceCasks()
{
  var elementNames = ['caskNo', 'anotherClass', 'yetAnotherClass']; // Add more class names as needed
  const regex = /cask no\. (?<caskid>[A-Z]*[0-9]+)\.[0-9]/i;
  
  elementNames.forEach(function(className) {
    var casks = document.getElementsByClassName(className);
    for (var i = 0, l = casks.length; i < l; i++) {
      it = casks[i].innerText;
      matches = it.match(regex).groups;
      if(matches !=null){
        name = codes[matches.caskid];
        casks[i].innerText = it + " (" + name + ")";
      }
    }
  });
}

// wait a bit - sometimes smws does dynamic loading
setTimeout(replaceCasks, 2000);